# Generated by Django 5.2.6 on 2025-11-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0003_alter_customer_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
