# Generated by Django 5.2.6 on 2025-11-30 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0004_alter_customer_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='post_code',
            new_name='postcode',
        ),
    ]
