# Generated by Django 5.2.6 on 2026-02-12 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('provision_type', models.CharField(choices=[('fixed', 'Fixed Amount (€)'), ('percent', 'Percentage (%)')], default='fixed', max_length=20)),
                ('provision_fixed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('provision_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage as decimal (e.g. 0.05 = 5%)', max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_type', models.CharField(choices=[('invoice', 'Invoice'), ('credit_note', 'Credit Note')], default='invoice', max_length=20)),
                ('invoice_status', models.CharField(choices=[('pending', 'Pending'), ('unpaid', 'Unpaid'), ('paid', 'Paid'), ('canceled', 'Canceled')], default='unpaid', max_length=20)),
                ('user_customer_id', models.IntegerField()),
                ('user_customer_number', models.CharField(max_length=10)),
                ('user_customer_first_name', models.CharField(max_length=100)),
                ('user_customer_last_name', models.CharField(max_length=100)),
                ('user_customer_street', models.CharField(max_length=200)),
                ('user_customer_street_number', models.CharField(max_length=10)),
                ('user_customer_postcode', models.CharField(max_length=20)),
                ('user_customer_city', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=255)),
                ('company_street', models.CharField(max_length=255)),
                ('company_number', models.CharField(max_length=20)),
                ('company_postcode', models.CharField(max_length=10)),
                ('company_city', models.CharField(max_length=100)),
                ('company_tax_number', models.CharField(max_length=50)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_bank', models.CharField(max_length=100)),
                ('company_bank_account', models.CharField(max_length=34)),
                ('company_swift_code', models.CharField(max_length=20)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='invoice_company_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('provision', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('investitions_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('business', models.ForeignKey(limit_choices_to={'type': 'business'}, on_delete=django.db.models.deletion.PROTECT, related_name='issued_invoices', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(limit_choices_to={'type': 'customer'}, on_delete=django.db.models.deletion.PROTECT, related_name='received_invoices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=200, null=True)),
                ('provision_type', models.CharField(choices=[('fixed', 'Fixed Amount (€)'), ('percent', 'Percentage (%)')], default='fixed', max_length=20)),
                ('provision_fixed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('provision_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage as decimal (e.g. 0.05 = 5%)', max_digits=10, null=True)),
                ('provision_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='invoice_app.invoice')),
            ],
        ),
    ]
