# Generated by Django 5.2.6 on 2025-12-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceservice',
            name='provision_fixed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoiceservice',
            name='provision_percent',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Percentage as decimal (e.g. 0.05 = 5%)', max_digits=10, null=True),
        ),
    ]
