# Generated by Django 5.2.6 on 2026-02-11 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='user_city',
            new_name='user_customer_city',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='user_first_name',
            new_name='user_customer_first_name',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='user_last_name',
            new_name='user_customer_last_name',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='user_number',
            new_name='user_customer_number',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='user_postcode',
            new_name='user_customer_postcode',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='user_street',
            new_name='user_customer_street',
        ),
    ]
