# Generated by Django 5.2.6 on 2025-11-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceservice',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='invoiceservice',
            name='investitions_amount',
        ),
        migrations.RemoveField(
            model_name='invoiceservice',
            name='provision',
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='investitions_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('unpaid', 'Unpaid'), ('paid', 'Paid'), ('canceled', 'Canceled')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='provision',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='value_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
