# Generated by Django 5.2.6 on 2026-02-13 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='company_number',
            new_name='company_street_number',
        ),
    ]
