# Generated by Django 5.2.6 on 2026-02-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0002_rename_company_number_invoice_company_street_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='MwSt', max_length=20)),
                ('percent', models.DecimalField(decimal_places=2, default=19.0, max_digits=5)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
