# Generated by Django 5.2.6 on 2026-02-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0002_rename_user_city_invoice_user_customer_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='user_customer_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
