# Generated by Django 5.2.6 on 2025-12-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0002_invoiceservice_provision_fixed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceservice',
            name='price_type',
            field=models.CharField(choices=[('fixed', 'Fixed Amount (€)'), ('percent', 'Percentage (%)')], default='fixed', max_length=20),
        ),
    ]
