# Generated by Django 5.2.6 on 2026-02-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0003_invoice_user_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='user_customer_id',
            field=models.IntegerField(),
        ),
    ]
