# Generated by Django 5.2.6 on 2025-12-04 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0003_invoiceservice_price_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicecatalog',
            old_name='price_type',
            new_name='provision_type',
        ),
    ]
