# Generated by Django 5.2.6 on 2026-02-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0003_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_amount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
