# Generated by Django 5.2.6 on 2025-11-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0003_alter_invoice_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
