# Generated by Django 5.2.6 on 2026-02-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0004_alter_invoice_user_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='user_customer_customer_number',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
