# Generated by Django 5.2.6 on 2026-02-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0004_invoice_discount_invoice_discount_amount_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='value_tax_amount',
            field=models.DecimalField(decimal_places=2, default=19, max_digits=10),
            preserve_default=False,
        ),
    ]
