# Generated by Django 5.2.6 on 2025-12-04 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0004_rename_price_type_servicecatalog_provision_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceservice',
            old_name='price_type',
            new_name='provision_type',
        ),
    ]
