# Generated by Django 5.2.6 on 2026-02-11 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0005_invoice_user_customer_customer_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='user_customer_customer_number',
        ),
    ]
