# Generated by Django 5.2.6 on 2026-03-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0005_invoice_value_tax_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('text', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='category',
            field=models.CharField(choices=[('course', 'Course'), ('service', 'Service')], default='course', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='notes_template',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('payu', 'payU')], default='paypal', max_length=20),
        ),
    ]
