# Generated by Django 5.2.6 on 2025-12-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0005_rename_price_type_invoiceservice_provision_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceservice',
            name='provision_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage as decimal (e.g. 0.05 = 5%)', max_digits=10, null=True),
        ),
    ]
