# Generated by Django 5.2.6 on 2026-01-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0006_alter_invoiceservice_provision_percent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicecatalog',
            old_name='amount_fixed',
            new_name='provision_fixed',
        ),
        migrations.RenameField(
            model_name='servicecatalog',
            old_name='name',
            new_name='service_name',
        ),
        migrations.RemoveField(
            model_name='invoiceservice',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='servicecatalog',
            name='amount_percent',
        ),
        migrations.AddField(
            model_name='servicecatalog',
            name='provision_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage as decimal (e.g. 0.05 = 5%)', max_digits=10, null=True),
        ),
    ]
