# Generated by Django 5.2.6 on 2026-03-12 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0006_textsnippet_invoice_category_invoice_notes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='category',
            new_name='invoice_category',
        ),
    ]
