# Generated by Django 5.2.6 on 2026-01-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0007_rename_amount_fixed_servicecatalog_provision_fixed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceservice',
            name='provision_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
