# Generated by Django 5.2.6 on 2026-01-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0008_invoiceservice_provision_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='customer_address',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_postcode',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_street',
            field=models.CharField(default='', max_length=200),
        ),
    ]
