# Generated by Django 5.2.6 on 2026-01-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0009_remove_invoice_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customer_city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer_first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer_last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer_postcode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer_street',
            field=models.CharField(max_length=200),
        ),
    ]
