# Generated by Django 5.2.6 on 2026-02-09 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_rename_prozentwert_discountcode_percent_value_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Section',
            new_name='Course',
        ),
    ]
