# Generated by Django 5.2.6 on 2026-04-23 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_rename_number_user_street_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='type',
            new_name='role',
        ),
    ]
