# Generated by Django 5.2.6 on 2026-01-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('name', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=20)),
                ('postcode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=255)),
                ('tax_number', models.CharField(max_length=50)),
                ('founding', models.CharField(default='')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('bank', models.CharField(max_length=100)),
                ('bank_account', models.CharField(max_length=34)),
                ('swift_code', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
