# Generated by Django 5.2.6 on 2026-02-05 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discountcode',
            old_name='Prozentwert',
            new_name='percent_value',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='Preis',
            new_name='price',
        ),
    ]
