# Generated by Django 5.2.6 on 2026-02-10 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0003_rename_section_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='section',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='section',
            new_name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='badge',
            field=models.CharField(blank=True, help_text='Example: "Most Popular", "Best Value", "New"', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/courses/'),
        ),
        migrations.AddField(
            model_name='course',
            name='order',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('de', 'Deutsch'), ('pl', 'Polnisch')], default='de', max_length=10),
        ),
        migrations.CreateModel(
            name='CourseFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('order', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='course_app.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
