# Generated by Django 5.2.6 on 2026-02-28 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0003_purchase_invoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
