# Generated by Django 5.2.6 on 2026-02-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0005_alter_coursefeature_course_alter_lesson_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/lessons/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('Deutsch', 'Deutsch'), ('Polnisch', 'Polnisch')], default='Deutsch', max_length=10),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
