# Generated by Django 5.2.6 on 2026-05-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0006_course_created_at_course_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
