# Generated by Django 5.2.6 on 2026-05-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0007_alter_lesson_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
