# Generated by Django 5.2.6 on 2026-02-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0008_course_status_discountcode_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountcode',
            name='status',
        ),
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
