# Generated by Django 5.2.6 on 2026-05-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0010_alter_lesson_created_at_alter_lesson_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
