# Generated by Django 5.2.6 on 2026-02-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='price',
            new_name='subtotal',
        ),
        migrations.AddField(
            model_name='purchase',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='purchase',
            name='paypal_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=129, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='total',
            field=models.DecimalField(decimal_places=2, default=124, max_digits=8),
            preserve_default=False,
        ),
    ]
