# Generated by Django 5.2.6 on 2026-02-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_app', '0003_purchase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='purchase',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=19, max_digits=5),
            preserve_default=False,
        ),
    ]
