# Generated by Django 5.2.6 on 2026-04-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_app', '0006_purchase_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
